### ISSUE TITLE
./build/bin missing

### ISSUE THREAD

**Issue by adampash** [hedgerh/chrome-react-webpack#2]
Hi! Was wondering what the build script looks like for this — it's not currently in the repo.

Thanks!
Adam

**Comment by hedgerh** [comment]
Hey @adampash, it's been a little while since I've shown this repo some love.  I'll sit down tonight and do some updating to get it in a good state.

In the meantime, I have a side project that has a more current build system set up.  It's not perfect, but it allows me to build out the app in a live reloading dev environment, or build it out for distribution.  Let me know if you have any questions, and I'll take a look at this repo tonight to see what I can update.

https://github.com/hedgerh/SoundcloudExtension

**Comment by adampash** [comment]
Cool, thanks v. much for the heads up! I'll give it a look.
